Traceback (most recent call last):
  File "C:\Users\USER\miniconda3\envs\ml_tf\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\USER\miniconda3\envs\ml_tf\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\USER\miniconda3\envs\ml_tf\lib\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\USER\miniconda3\envs\ml_tf\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\USER\miniconda3\envs\ml_tf\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\USER\miniconda3\envs\ml_tf\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\USER\miniconda3\envs\ml_tf\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
beer_df['DEF'] = double_exp_smoothing(beer_df['Beer_Prod'], 0.4, 0.7)
beer_df['Single_Exponential_Forecast'] = single_exp_smoothing(beer_df['Beer_Prod'], 0.4)

fig, ax = plt.subplots()
fig.set_size_inches(5, 5)
beer_df['Beer_Prod'].iloc[:45].plot(color='b', linestyle = '-', label = 'Beer Prod.')
beer_df['DEF'].iloc[:45].plot(color='r', linestyle = '--', label = r'DES $\alpha=0.4,\,\beta=0.7$')
beer_df['Single_Exponential_Forecast'].iloc[:45].plot(color='k', linestyle = '-.', label = r'SES $\alpha=0.4$')
leg = ax.legend();
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[65], line 2[0m
[0;32m      1[0m beer_df[[38;5;124m'[39m[38;5;124mDEF[39m[38;5;124m'[39m] [38;5;241m=[39m double_exp_smoothing(beer_df[[38;5;124m'[39m[38;5;124mBeer_Prod[39m[38;5;124m'[39m], [38;5;241m0.4[39m, [38;5;241m0.7[39m)
[1;32m----> 2[0m beer_df[[38;5;124m'[39m[38;5;124mSingle_Exponential_Forecast[39m[38;5;124m'[39m] [38;5;241m=[39m [43msingle_exp_smoothing[49m(beer_df[[38;5;124m'[39m[38;5;124mBeer_Prod[39m[38;5;124m'[39m], [38;5;241m0.4[39m)
[0;32m      4[0m fig, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots()
[0;32m      5[0m fig[38;5;241m.[39mset_size_inches([38;5;241m5[39m, [38;5;241m5[39m)

[1;31mNameError[0m: name 'single_exp_smoothing' is not defined

